### PR TITLE
Fix: Enable adapter only if jest installed

### PR DESCRIPTION
**Pull request by marilari88**

### CODE REVIEW

**Review by haydenmeade — APPROVED** [review]

**Comment by jigfox** [comment]
instead of looking for direct dependency, it would be better to look if `node_modules/.bin/jest` exists, because it could be a peerDependency or even a child dependency

**Comment by marilari88** [comment]
Hi @jigfox, thanks for sharing your thoughts,
Initially, I considered your solution and I think it's good, but IMHO there are very little cons:
- Adapter won't be enabled if dependencies are not yet installed. (user could be interested in working on a JS project and read the tests list before or during dependencies installation)
- In some monorepos dependencies can be shared among packages/apps and as a consequence, you couldn't find jest executable in .bin folder of the single package/app

About your suggestion, We can look also for peerDependency in the package.json and I don't think We should enable neotest-jest in case of Jest is installed as a child dep. I struggle to find a real case it could happen. Please tell me if you're not convinced

**Comment by hori-ryota** [comment]
@haydenmeade @marilari88 Can you merge this?

**Comment by marilari88** [comment]
> @haydenmeade @marilari88 Can you merge this?

I have no permission to merge this. Sorry

**Comment by entropitor** [comment]
> In some monorepos dependencies can be shared among packages/apps and as a consequence, you couldn't find jest executable in .bin folder of the single package/app

Can we revise how this is done given it's breaking monorepos? https://github.com/nvim-neotest/neotest-jest/issues/60

**Pull request merged**
